/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.time.LocalDateTime;

public class App {
    public String name = "";
    
    public String getGreeting() {
        return "Hello World! This is gradle job created by Subodh at -  ";
    }
    public void setName(String name) {
        this.name = name;
    }
    public String getName() {
        return name;
    }
    
    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        // Get the current date and time
    LocalDateTime now = LocalDateTime.now();

    // Format and display the date and time
    System.out.println(now.toString());    
    }
}
